name: "Run PHPUnit tests"

on:
  push:
    branches:
      - master
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
    pull-requests: read

jobs:
    main:
        name: Run PHPUnit tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Run PHPUnit tests
          run: |
            composer install
            vendor/bin/phpunit